// Generated by Wrangler on Fri May 03 2024 13:05:36 GMT-0500 (hora estándar de Colombia)
// by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://gjcpczwrwrfgfxouxkkg.supabase.co";
	SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqY3Bjendyd3JmZ2Z4b3V4a2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ3NTczNTksImV4cCI6MjAzMDMzMzM1OX0.ADloQmf8MDgmsZYUESfqKrigSaHDalfsixzKhIEQoWk";
	SECRET_KEY: "31b050193ea5d8f7f6429cbbb07d9fca";
}
