// Generated by Wrangler on Tue Apr 30 2024 18:53:39 GMT-0500 (hora estándar de Colombia)
// by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://uxvjdvlzkrtskzqcmmif.supabase.co";
	SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dmpkdmx6a3J0c2t6cWNtbWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQyMzUxNDYsImV4cCI6MjAyOTgxMTE0Nn0.eNWTfQDkl0SjJFKXCTuQ0PgxdGH8E-gMjTrsQOrciJY";
	SECRET_KEY: "31b050193ea5d8f7f6429cbbb07d9fca";
}
